image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - main
  script:
    - npm install
    - npm run build

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public

cache:
  paths:
    - node_modules
