image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - main
  script:
    - npm install
    - npm run build

pages:
  stage: deploy
  only:
    - main
  script:
    - rm -rf public
    - mkdir .public
    - cp -rf .public
    - mv .public public
  artifacts:
    paths:
      - public

cache:
  paths:
    - node_modules
